name: Deploy Streamlit App

on:
  push:
    branches: [ main, development ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          
          # Navigate to app directory
          cd /var/www/timeclockchecker || { echo "App directory not found"; exit 1; }
          
          # Pull latest changes
          echo "Pulling latest changes..."
          git pull origin ${{ github.ref_name }} || { echo "Git pull failed"; exit 1; }
          
          # Activate virtual environment and install/update dependencies
          echo "Installing dependencies..."
          source venv/bin/activate || { echo "Virtual environment not found"; exit 1; }
          pip install -r requirements.txt || { echo "Dependency installation failed"; exit 1; }
          
          # Restart systemd service
          echo "Restarting service..."
          sudo systemctl restart timeclockchecker || { echo "Service restart failed"; exit 1; }
          
          # Wait for service to start
          sleep 5
          
          # Check service status
          echo "Checking service status..."
          sudo systemctl is-active --quiet timeclockchecker || { echo "Service failed to start"; sudo journalctl -u timeclockchecker --lines=20; exit 1; }
          
          echo "✅ Deployment successful!"